@startuml
'https://plantuml.com/class-diagram

class PlayingGrid{
+plcards : GameCard[81][81]
+numElements : int[7]
+lastPlacedCard : GameCard

List<Coordinate> getPlaceablePositions(i : int, j : int)
int place(i : int, j : int, card : GameCard)
GameCard getLastPlacedCard()
GameCard getPlacedCard(i : int, j : int)
GameCard[81][81] getPlacedCards()
int getNumElement(e : Element)
int[7] getNumElements()
int computePoints()
Boolean checkCardPlaceability(c : GameCard)

int checkPatterns(patternCard : PatternObjectiveCard)
Boolean cellIsEmpty(row : int, column : int)
Boolean checkColourMatch(row : int, column : int, patternCard: PatternObjectiveCard, coordReqPatternIndex : int)
Boolean cardWasAlreadyUsedForThisObjective (row : int, column : int, patternCard : PatternObjectiveCard)
void markCardAsUsedForThisObjective(row : int, column : int, patternCard : PatternObjectiveCard)
int checkElements(elementCard : ElementObjectiveCard)
}

note left of PlayingGrid::getNumElements{
returns an array of 7 int counters representing
the number of each type of element currently owned by the player
}




class Player{
+colour : PlayerColour
+nickname : String
+points : int
+cardsInHand : List<GameCard>
+objCard : ObjectiveCard

ObjectiveCard getObjectiveCard()
List<GameCard> getCardsInHand()
PlayingGrid getPlayingGrid()
String getNickname()
void addCartInHand(Gamecard c)
void setObjectiveCard(ObjectiveCard oc)
int getPoints()
void setColour(Colour colour)
void placePlayingGrid(int i, int j, Gamecard c)
}

class Match {
    + numPlayers : int
    + remainingRounds : int
    + playerOrder : List<Player>
    + playerTurn : int
    + publicObj : ObjectiveCard[2]
    + startDeck : List<StartCard>
    + objDeck : List<ObjectiveCard>

    int getNumPlayers()
    List<String> getPlayerNames();
    List<String> getCardsInHand(nickname : String)
    int getSecretObjective(nickname : String)
    int[2] getPublicObjectives()
    List<Coordinate> getPlaceablePositions(x : int, y : int)

    void addPlayer(nickname : String)
    void randomizePlayerOrder()
    void createDecks()
    void assignStartCards()
    void placeStartCards(selectedSides : Map<String, Boolean>)
    void setPlayerColors(selectedColors : Map<String, PlayerColor>)
    void drawObjective()
    void distributeCards()
    void setPlayerObjectives(selectedObjectives : Map<String, Boolean>)
    void placeCard(index : int, side : boolean, xpos : int, ypos : int)
    void drawCard(index : int)
    int nextTurn()
    Boolean checkEndgameCondition()
}
note right of Match::createDecks
    this method creates the cards and
    puts them in their decks (JSON/XML
    to be defined)
end note

Match --> Player
Match --> DrawTable

class GameModel{
    +listeners : List<ModelListener>
    void addListener(listener : ModelListener)
    void addPlayersToMatch(nicknames : List<String>)
    void placeStartCards(selectedSides : Map<String, Boolean>)
    void setPlayerColors(selectedColors : Map<String, PlayerColor>)
    void distributeCards()
    void setPlayerObjectives(selectedObjectives : Map<String, Boolean>)
    void selectPlacingPosition(x : int, y : int)
    void placeCard(index : int, side : boolean, xpos : int, ypos : int)
    void drawCard(index : int)
    void nextTurn()
}
note right of GameModel
    These are the methods available to the Controller.
    At the end of each method,
    the Model will notify the Controller (subscribed as a listener)
    about the changes in the state.
    These methods validate the parameters and invoke the methods
    of the class Match, which contains the actual state of the match.
end note

GameModel --> Match

Player --> PlayingGrid

enum PlayerColor{
RED
YELLOW
GREEN
BLUE
}
PlayerColor <-- Player

class DrawTable{
 +gold1 : GoldCard
 +gold2 : GoldCard
 +res1 : ResourceCard
 +res2 : ResourceCard
 +goldDeck : List<GoldCard>
 +resDeck : List<ResourceCard>

 void initializeGoldDeck()
 void initializeResourceDeck()
 GameCard[4] getPublicCards()
 String getColorTopGoldDeck()
 String getColorTopResDeck()
 GameCard drawCard(i : int)
}

class ElementsObjectiveCard{
 +reqElements : int[7]
 int[] getReqElements()
}

class PatternObjectiveCard{
    +coordReqPattern : CoordinateSubMatrix[3]
    +deltaXSecond : int
    +deltaYSecond : int
    +deltaXThird : int
    +deltaYThird : int

    void calculateDeltas()
    CoordinateSubMatrix getCoordReqPattern(arrayIndex : int)
    int getDeltaXSecond()
    int getDeltaYSecond()
    int getDeltaXThird()
    int getDeltaYThird()
}

note left of PatternObjectiveCard::coordReqPattern{
The pattern required to get points
is expressed as an array of 3 Coordinate
objects, representing the coordinates
and colours of the cards required by the
pattern, which can be seen either as a
3x3 submatrix or a 4x2 submatrix.
The coordinates represent the positions
of the cards in the submatrix.
}



class ObjectiveCard{
    +objIndex : int
    void setObjIndex()
    int getObjIndex()
}

ObjectiveCard <|-- ElementsObjectiveCard
ObjectiveCard <|-- PatternObjectiveCard


class GameCard{
+index : int
+front : Side
+back : Side
+validSide : Side
+coordinate : Coordinate
+flagObj : Boolean[8]

Side getValidSide()
void setValidSide(side : Boolean)
int getPoints()
Boolean isThereCorner(i : int)
Element getResourceCorner(i : int)
String getColour()
int[7] getResources()
Condition getCondition()
int[7] getRequirements()
Coordinate getCoordinates()
void setCoordinates(Coordinate c)
Boolean getCompleteObjFlag(patternObjIndex : int)
void setCompleteObjFlag(patternObjIndex : int)
}

class GoldCard{
    +colour : String
    String getColour()
    Boolean getCompleteObjFlag(patternObjIndex : int)
    void setCompleteObjFlag(patternObjIndex : int)
}
class ResourceCard{
    +colour : String
    String getColour();
    Boolean getCompleteObjFlag(patternObjIndex : int)
    void setCompleteObjFlag(patternObjIndex : int)
}

GameCard <|-- GoldCard
GameCard <|-- StartCard
GameCard <|-- ResourceCard

abstract class Side{
+corners : Corner[4]
+points : int
Corner getCorner(i : int)
int getPoints()
List<Element> getRequirements()
Condition getCondition()
abstract List<Element> getCenter()
}

class GoldFront{
+requirements : List<Element>
List<Element> getRequirements()
Condition getCondition()
List<Element> getCenter()
}

class NotGoldFront{
List<Element> getCenter()
}

class StartBack{
+center : List<Element>
List<Element> getCenter()
}

class ColouredBack{
+center: Element
List<Element> getCenter()
}
note left of GameCard::flagObj{
array of 8 boolean flags initialized to false:
each flag can be set to true if this instance
of a GoldCard object is used to count a
pattern objective card
e.g. flagObj[4] is set to true is this instance
of a GoldCard is used to count pattern objective
number 4 in the deck.
}


Side <|-- GoldFront
Side <|-- NotGoldFront
Side <|-- StartBack
Side <|-- ColouredBack

class Corner{
+elem : Element
Element getElement()
}

GameCard *- Side
Side *- Corner
Corner --> Element

enum Element {
ANIMAL
FUNGUS
PLANT
INSECT
MANUSCRIPT
INKWELL
QUILL
}

PatternObjectiveCard --> CoordinateSubMatrix

class CoordinateSubMatrix{
     +x : int
     +y : int
     +colour : String

     int getX()
     void setX(x : int)
     int getY()
     void setY(y : int)
     String getColour()
     void setColour(colour : String)
}

GoldFront --> Condition

class Condition{
    +type : String
    +object : Element

    String getType()
    Element getObject()
}
@enduml